[2025-06-25T08:04:19.446+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-25T08:04:19.477+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_unai_step1_git_20250625T075407.scp_to_hpc manual__2025-06-25T08:04:08.895416+00:00 [queued]>
[2025-06-25T08:04:19.488+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_unai_step1_git_20250625T075407.scp_to_hpc manual__2025-06-25T08:04:08.895416+00:00 [queued]>
[2025-06-25T08:04:19.489+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-25T08:04:19.504+0000] {taskinstance.py:2890} INFO - Executing <Task(SSHOperator): scp_to_hpc> on 2025-06-25 08:04:08.895416+00:00
[2025-06-25T08:04:19.510+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-25T08:04:19.512+0000] {standard_task_runner.py:72} INFO - Started process 90 to run task
[2025-06-25T08:04:19.513+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_unai_step1_git_20250625T075407', 'scp_to_hpc', 'manual__2025-06-25T08:04:08.895416+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/test_unai_step1_git_20250625T075407.py', '--cfg-path', '/tmp/tmpbrvr1urh']
[2025-06-25T08:04:19.515+0000] {standard_task_runner.py:105} INFO - Job 372: Subtask scp_to_hpc
[2025-06-25T08:04:19.562+0000] {task_command.py:467} INFO - Running <TaskInstance: test_unai_step1_git_20250625T075407.scp_to_hpc manual__2025-06-25T08:04:08.895416+00:00 [running]> on host 1cabd79ac10f
[2025-06-25T08:04:19.665+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Unai Motriko' AIRFLOW_CTX_DAG_ID='test_unai_step1_git_20250625T075407' AIRFLOW_CTX_TASK_ID='scp_to_hpc' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T08:04:08.895416+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T08:04:08.895416+00:00'
[2025-06-25T08:04:19.666+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-25T08:04:19.667+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-25T08:04:19.668+0000] {logging_mixin.py:190} INFO - Current task name:scp_to_hpc state:running start_date:2025-06-25 08:04:19.478395+00:00
[2025-06-25T08:04:19.668+0000] {logging_mixin.py:190} INFO - Dag name:test_unai_step1_git_20250625T075407 and current dag run status:running
[2025-06-25T08:04:19.669+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-25T08:04:19.669+0000] {ssh.py:123} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-06-25T08:04:19.679+0000] {base.py:84} INFO - Retrieving connection 'hpc_ssh'
[2025-06-25T08:04:19.680+0000] {ssh.py:286} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-06-25T08:04:19.737+0000] {transport.py:1944} INFO - Connected (version 2.0, client OpenSSH_8.0)
[2025-06-25T08:04:20.390+0000] {transport.py:1944} INFO - Authentication (password) successful!
[2025-06-25T08:04:20.394+0000] {ssh.py:432} INFO - Running command: scp -r /tmp/repo umotriko@10.75.0.21:.
[2025-06-25T08:04:26.902+0000] {ssh.py:483} WARNING - Permission denied, please try again.
[2025-06-25T08:04:26.909+0000] {ssh.py:483} WARNING - Permission denied, please try again.
[2025-06-25T08:04:26.917+0000] {ssh.py:483} WARNING - umotriko@10.75.0.21: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[2025-06-25T08:04:26.920+0000] {ssh.py:483} WARNING - lost connection
[2025-06-25T08:04:26.991+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/operators/ssh.py", line 161, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/operators/ssh.py", line 155, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2025-06-25T08:04:26.998+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-25T08:04:26.998+0000] {logging_mixin.py:190} INFO - Task start:2025-06-25 08:04:19.478395+00:00 end:2025-06-25 08:04:26.997610+00:00 duration:7.519215
[2025-06-25T08:04:26.999+0000] {logging_mixin.py:190} INFO - Task:<Task(SSHOperator): scp_to_hpc> dag:<DAG: test_unai_step1_git_20250625T075407> dagrun:<DagRun test_unai_step1_git_20250625T075407 @ 2025-06-25 08:04:08.895416+00:00: manual__2025-06-25T08:04:08.895416+00:00, state:running, queued_at: 2025-06-25 08:04:08.920513+00:00. externally triggered: True>
[2025-06-25T08:04:27.000+0000] {logging_mixin.py:190} INFO - Failure caused by SSH operator error: exit status = 1
[2025-06-25T08:04:27.000+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=test_unai_step1_git_20250625T075407, task_id=scp_to_hpc, run_id=manual__2025-06-25T08:04:08.895416+00:00, execution_date=20250625T080408, start_date=20250625T080419, end_date=20250625T080426
[2025-06-25T08:04:27.248+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-25T08:04:27.249+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 372 for task scp_to_hpc (SSH operator error: exit status = 1; 90)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/operators/ssh.py", line 161, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/operators/ssh.py", line 155, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2025-06-25T08:04:27.298+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-25T08:04:27.315+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-25T08:04:27.317+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
